packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: ^0.560.0
  tailwindcss: ^4.1.18
  "@tailwindcss/postcss": ^4.1.18
  eslint: ^9.39.2
  "@eslint/js": ^9.39.2
  prettier: ^3.7.4
  typescript: ^5.9.3
  "@types/node": ^25.0.3
  "@types/eslint": ^9
  "typescript-eslint": ^8.49.0
  "vite": ^7.2.7

catalogs:
  react19:
    react: 19.2.3
    react-dom: 19.2.3
    "@types/react": ^19.2
    "@types/react-dom": ^19.2